-- ============================================
-- Seed: segment_averages from historical CSV
-- Generated: 2026-03-26T20:36:51.837Z
-- Source records: 688 (skipped: 0)
-- ============================================

delete from public.segment_averages;

insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', true, false, 'financial', 3.09, 247.33, 80);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', true, false, 'health', 3.11, 249.00, 80);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', true, false, 'family', 4.05, 324.00, 80);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', true, false, 'relationship', 3.86, 309.00, 80);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', true, false, 'spiritual', 3.95, 315.67, 80);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', true, false, 'professional', 3.88, 310.67, 80);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', true, false, 'social', 3.53, 282.33, 80);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', true, false, 'leisure', 3.07, 245.67, 80);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', false, false, 'financial', 2.58, 56.67, 22);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', false, false, 'health', 3.21, 70.67, 22);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', false, false, 'family', 3.74, 82.33, 22);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', false, false, 'relationship', 3.50, 77.00, 22);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', false, false, 'spiritual', 3.92, 86.33, 22);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', false, false, 'professional', 3.82, 84.00, 22);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', false, false, 'social', 3.85, 84.67, 22);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', false, false, 'leisure', 3.23, 71.00, 22);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', false, false, 'financial', 2.91, 139.67, 48);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', false, false, 'health', 3.51, 168.67, 48);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', false, false, 'family', 3.85, 184.67, 48);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', false, false, 'relationship', 3.72, 178.67, 48);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', false, false, 'spiritual', 3.84, 184.33, 48);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', false, false, 'professional', 3.64, 174.67, 48);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', false, false, 'social', 3.37, 161.67, 48);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', false, false, 'leisure', 3.24, 155.67, 48);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', false, false, 'financial', 3.11, 56.00, 18);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', false, false, 'health', 3.54, 63.67, 18);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', false, false, 'family', 4.17, 75.00, 18);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', false, false, 'relationship', 4.11, 74.00, 18);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', false, false, 'spiritual', 4.26, 76.67, 18);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', false, false, 'professional', 3.83, 69.00, 18);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', false, false, 'social', 3.85, 69.33, 18);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', false, false, 'leisure', 3.80, 68.33, 18);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', false, false, 'financial', 2.94, 32.33, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', false, false, 'health', 3.64, 40.00, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', false, false, 'family', 4.18, 46.00, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', false, false, 'relationship', 4.24, 46.67, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', false, false, 'spiritual', 4.36, 48.00, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', false, false, 'professional', 3.58, 39.33, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', false, false, 'social', 3.97, 43.67, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', false, false, 'leisure', 3.36, 37.00, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', false, true, 'financial', 2.63, 42.00, 16);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', false, true, 'health', 3.00, 48.00, 16);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', false, true, 'family', 3.96, 63.33, 16);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', false, true, 'relationship', 3.71, 59.33, 16);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', false, true, 'spiritual', 4.10, 65.67, 16);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', false, true, 'professional', 3.60, 57.67, 16);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', false, true, 'social', 3.31, 53.00, 16);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', false, true, 'leisure', 2.67, 42.67, 16);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', true, false, 'financial', 3.05, 350.67, 115);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', true, false, 'health', 3.47, 399.00, 115);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', true, false, 'family', 4.06, 467.00, 115);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', true, false, 'relationship', 3.93, 452.00, 115);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', true, false, 'spiritual', 4.19, 482.33, 115);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', true, false, 'professional', 3.81, 438.33, 115);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', true, false, 'social', 3.66, 421.33, 115);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', true, false, 'leisure', 3.29, 378.67, 115);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', true, true, 'financial', 2.91, 148.33, 51);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', true, true, 'health', 3.08, 157.33, 51);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', true, true, 'family', 3.98, 203.00, 51);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', true, true, 'relationship', 3.90, 198.67, 51);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', true, true, 'spiritual', 4.07, 207.67, 51);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', true, true, 'professional', 3.81, 194.33, 51);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', true, true, 'social', 3.29, 168.00, 51);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', true, true, 'leisure', 3.08, 157.33, 51);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', true, false, 'financial', 2.52, 63.00, 25);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', true, false, 'health', 3.13, 78.33, 25);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', true, false, 'family', 3.57, 89.33, 25);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', true, false, 'relationship', 3.84, 96.00, 25);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', true, false, 'spiritual', 3.99, 99.67, 25);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', true, false, 'professional', 3.67, 91.67, 25);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', true, false, 'social', 3.43, 85.67, 25);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', true, false, 'leisure', 3.03, 75.67, 25);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', true, true, 'financial', 2.33, 4.67, 2);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', true, true, 'health', 3.00, 6.00, 2);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', true, true, 'family', 4.17, 8.33, 2);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', true, true, 'relationship', 4.83, 9.67, 2);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', true, true, 'spiritual', 5.00, 10.00, 2);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', true, true, 'professional', 3.83, 7.67, 2);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', true, true, 'social', 3.50, 7.00, 2);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen Z', true, true, 'leisure', 2.50, 5.00, 2);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', false, false, 'financial', 2.77, 174.67, 63);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', false, false, 'health', 3.47, 218.67, 63);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', false, false, 'family', 3.74, 235.67, 63);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', false, false, 'relationship', 3.80, 239.67, 63);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', false, false, 'spiritual', 3.98, 251.00, 63);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', false, false, 'professional', 3.70, 233.33, 63);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', false, false, 'social', 3.67, 231.00, 63);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', false, false, 'leisure', 3.29, 207.00, 63);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', true, false, 'financial', 2.77, 36.00, 13);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', true, false, 'health', 3.08, 40.00, 13);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', true, false, 'family', 4.10, 53.33, 13);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', true, false, 'relationship', 3.64, 47.33, 13);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', true, false, 'spiritual', 3.85, 50.00, 13);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', true, false, 'professional', 3.90, 50.67, 13);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', true, false, 'social', 3.13, 40.67, 13);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', true, false, 'leisure', 3.23, 42.00, 13);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', true, true, 'financial', 3.03, 142.33, 47);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', true, true, 'health', 3.57, 167.67, 47);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', true, true, 'family', 4.34, 204.00, 47);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', true, true, 'relationship', 4.21, 198.00, 47);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', true, true, 'spiritual', 4.35, 204.67, 47);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', true, true, 'professional', 3.89, 182.67, 47);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', true, true, 'social', 3.75, 176.33, 47);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', true, true, 'leisure', 3.36, 158.00, 47);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', true, true, 'financial', 2.64, 142.67, 54);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', true, true, 'health', 3.14, 169.67, 54);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', true, true, 'family', 4.14, 223.33, 54);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', true, true, 'relationship', 3.89, 210.00, 54);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', true, true, 'spiritual', 4.12, 222.67, 54);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', true, true, 'professional', 3.64, 196.67, 54);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', true, true, 'social', 3.50, 189.00, 54);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', true, true, 'leisure', 2.89, 156.00, 54);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', true, true, 'financial', 3.12, 190.33, 61);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', true, true, 'health', 3.11, 189.67, 61);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', true, true, 'family', 4.23, 258.33, 61);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', true, true, 'relationship', 3.98, 242.67, 61);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', true, true, 'spiritual', 4.24, 258.67, 61);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', true, true, 'professional', 4.25, 259.00, 61);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', true, true, 'social', 3.44, 210.00, 61);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', true, true, 'leisure', 3.10, 189.33, 61);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', false, true, 'financial', 2.50, 25.00, 10);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', false, true, 'health', 3.53, 35.33, 10);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', false, true, 'family', 3.40, 34.00, 10);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', false, true, 'relationship', 3.57, 35.67, 10);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', false, true, 'spiritual', 3.77, 37.67, 10);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', false, true, 'professional', 3.27, 32.67, 10);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', false, true, 'social', 3.57, 35.67, 10);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Millennial', false, true, 'leisure', 3.47, 34.67, 10);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Boomer', true, true, 'financial', 3.04, 27.33, 9);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Boomer', true, true, 'health', 3.11, 28.00, 9);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Boomer', true, true, 'family', 3.67, 33.00, 9);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Boomer', true, true, 'relationship', 3.70, 33.33, 9);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Boomer', true, true, 'spiritual', 3.81, 34.33, 9);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Boomer', true, true, 'professional', 3.67, 33.00, 9);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Boomer', true, true, 'social', 3.63, 32.67, 9);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Boomer', true, true, 'leisure', 3.15, 28.33, 9);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', false, true, 'financial', 2.67, 2.67, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', false, true, 'health', 2.33, 2.33, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', false, true, 'family', 4.00, 4.00, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', false, true, 'relationship', 3.33, 3.33, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', false, true, 'spiritual', 4.00, 4.00, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', false, true, 'professional', 2.00, 2.00, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', false, true, 'social', 5.00, 5.00, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', false, true, 'leisure', 3.33, 3.33, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', false, true, 'financial', 1.78, 5.33, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', false, true, 'health', 2.78, 8.33, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', false, true, 'family', 3.33, 10.00, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', false, true, 'relationship', 3.89, 11.67, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', false, true, 'spiritual', 3.44, 10.33, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', false, true, 'professional', 2.33, 7.00, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', false, true, 'social', 2.67, 8.00, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Millennial', false, true, 'leisure', 1.56, 4.67, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', true, false, 'financial', 3.27, 36.00, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', true, false, 'health', 3.18, 35.00, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', true, false, 'family', 4.33, 47.67, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', true, false, 'relationship', 4.00, 44.00, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', true, false, 'spiritual', 4.15, 45.67, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', true, false, 'professional', 4.09, 45.00, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', true, false, 'social', 4.03, 44.33, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', true, false, 'leisure', 3.52, 38.67, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', true, false, 'financial', 3.36, 37.00, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', true, false, 'health', 3.27, 36.00, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', true, false, 'family', 3.91, 43.00, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', true, false, 'relationship', 4.15, 45.67, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', true, false, 'spiritual', 4.30, 47.33, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', true, false, 'professional', 3.73, 41.00, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', true, false, 'social', 3.73, 41.00, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Gen X', true, false, 'leisure', 3.30, 36.33, 11);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', false, true, 'financial', 2.33, 14.00, 6);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', false, true, 'health', 3.61, 21.67, 6);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', false, true, 'family', 4.56, 27.33, 6);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', false, true, 'relationship', 4.44, 26.67, 6);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', false, true, 'spiritual', 4.44, 26.67, 6);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', false, true, 'professional', 3.89, 23.33, 6);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', false, true, 'social', 4.22, 25.33, 6);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', false, true, 'leisure', 3.17, 19.00, 6);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Boomer', true, true, 'financial', 3.00, 9.00, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Boomer', true, true, 'health', 3.78, 11.33, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Boomer', true, true, 'family', 4.11, 12.33, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Boomer', true, true, 'relationship', 4.22, 12.67, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Boomer', true, true, 'spiritual', 4.67, 14.00, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Boomer', true, true, 'professional', 4.11, 12.33, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Boomer', true, true, 'social', 3.11, 9.33, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Boomer', true, true, 'leisure', 4.44, 13.33, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', false, false, 'financial', 2.33, 7.00, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', false, false, 'health', 3.22, 9.67, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', false, false, 'family', 2.78, 8.33, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', false, false, 'relationship', 2.89, 8.67, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', false, false, 'spiritual', 3.56, 10.67, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', false, false, 'professional', 3.00, 9.00, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', false, false, 'social', 3.78, 11.33, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', false, false, 'leisure', 3.00, 9.00, 3);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', true, true, 'financial', 1.67, 3.33, 2);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', true, true, 'health', 2.00, 4.00, 2);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', true, true, 'family', 3.00, 6.00, 2);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', true, true, 'relationship', 3.50, 7.00, 2);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', true, true, 'spiritual', 3.83, 7.67, 2);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', true, true, 'professional', 2.83, 5.67, 2);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', true, true, 'social', 3.67, 7.33, 2);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen Z', true, true, 'leisure', 2.67, 5.33, 2);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Boomer', false, false, 'financial', 3.33, 3.33, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Boomer', false, false, 'health', 3.00, 3.00, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Boomer', false, false, 'family', 3.67, 3.67, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Boomer', false, false, 'relationship', 4.33, 4.33, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Boomer', false, false, 'spiritual', 4.00, 4.00, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Boomer', false, false, 'professional', 4.00, 4.00, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Boomer', false, false, 'social', 3.67, 3.67, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Mujer', 'Boomer', false, false, 'leisure', 3.67, 3.67, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', false, false, 'financial', 4.00, 4.00, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', false, false, 'health', 4.00, 4.00, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', false, false, 'family', 5.00, 5.00, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', false, false, 'relationship', 4.00, 4.00, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', false, false, 'spiritual', 4.33, 4.33, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', false, false, 'professional', 3.33, 3.33, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', false, false, 'social', 4.00, 4.00, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Hombre', 'Gen X', false, false, 'leisure', 4.00, 4.00, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', true, false, 'financial', 4.00, 4.00, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', true, false, 'health', 4.67, 4.67, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', true, false, 'family', 4.33, 4.33, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', true, false, 'relationship', 4.33, 4.33, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', true, false, 'spiritual', 4.67, 4.67, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', true, false, 'professional', 4.33, 4.33, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', true, false, 'social', 4.00, 4.00, 1);
insert into public.segment_averages (gender, generation, has_partner, has_children, area_code, avg_score, total_score, sample_size) values ('Otro', 'Millennial', true, false, 'leisure', 4.00, 4.00, 1);

-- Total rows inserted: 224
